server {
    listen 127.0.0.1:8080;
    server_name primary;
    client_max_body_size 1024;     # 1 KB — small, so we can prove 413

    location / {
        root www;
        methods GET POST;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name secondary;
    client_max_body_size 1m;       # 1 MB

    location / {
        root www;
        methods GET POST;
    }
}
